apiVersion: v1
kind: Service
metadata:
  name: fisap-service
spec:
  selector:
    app: fisap
  ports:
    - name: http
      port: 8081  
      targetPort: 8080
      nodePort: 30080  
  type: NodePort