version: "3"

services:
  server:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
    - ../../:/go/src/github.com/cryptobranchoidea/fisap
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}