# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    paths:
     - .github/**
     - server/**
    branches: [ "dev","main" ]
  pull_request:
    paths:
     - .github/**
     - server/**
    branches: [ "dev","main" ]

jobs:

  build:
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: cd server && go build -v ./...

    - name: Test
      run: cd server && go test -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}