name: "/rerun-lint"
on:
  issue_comment:
    types: [created, edited]

jobs:
  manual_plan:
    name: "rerun lint"
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/rerun lint')
    runs-on: [ubuntu-latest]
    steps:
        - name: get upstream branch
          id: upstreambranch
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
  
        - name: Checkout upstream repo
          uses: actions/checkout@v2
          with:
            ref: ${{ steps.upstreambranch.outputs.branchname }}

        - uses: actions/setup-go@v4
          with:
            go-version: '1.20'
            cache: false
        - uses: actions/checkout@v3
            
        - id: rerun-lint
          uses: reviewdog/action-golangci-lint@v2
          with:
           workdir: ./server
    
        - name: plan success message
          uses: actions/github-script@0.9.0
          if: steps.rerun-lint.outputs.exitcode == 0
          env:
            STDOUT: "```${{ steps.rerun-lint.outputs.stdout }}```"
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "#### `test rerun` Success\n" + process.env.STDOUT
                })
        