name: "/rerun-test"
on:
  issue_comment:
    types: [created, edited]

jobs:
  manual_plan:
    name: "rerun test"
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/rerun')
    runs-on: [ubuntu-latest]
    steps:
        - name: comment
          uses: actions/github-script@v5
          env:
           MESSAGE: |
            テストを再実行します。
          with:
           script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
        - name: get upstream branch
          id: upstreambranch
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
  
        - name: Checkout upstream repo
          uses: actions/checkout@v2
          with:
            ref: ${{ steps.upstreambranch.outputs.branchname }}

        - uses: actions/checkout@v3

        - name: set up Go 1.x
          uses: actions/setup-go@v3
          with:
            go-version: 1.20
            
        - id: rerun-test
          run: |
            cd server && go build -v ./...
            cd server && go test ./...
    
        - name: plan success message
          uses: actions/github-script@0.9.0
          if: steps.rerun-test.outputs.exitcode == 0
          env:
            STDOUT: "```${{ steps.rerun-test.outputs.stdout }}```"
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "#### `test rerun` Success\n" + process.env.STDOUT
                })
        